name = "paperframe-api"
main = "src/index.ts"
compatibility_date = "2022-09-07"

workers_dev = true

r2_buckets = [
  { binding = 'STORAGE', bucket_name = 'paperframe', preview_bucket_name = 'paperframe-preview' }
]

kv_namespaces = [
  { binding = 'METADATA', id = 'e9cc7d31dab94e12846d890778ac74b3', preview_id = '01ec45005d4748c09bb3a7c80cb17008' }
]

route = 'paperframe.tsmith.photos/api*'

[triggers]
crons = ["*/5 * * * *"]

[vars]
# API_ADMIN_USER (secret)
# API_ADMIN_PASS (secret)
